<?php

/**
 * @file
 * Contains bing_maps_api.
 */

use Drupal\Core\Template\Attribute;

/**
 * Implements hook_theme().
 */
function bing_maps_api_theme() {
  return [
    'bing_maps_api_search_item' => [
      'variables' => [
        'lat' => '',
        'long' => '',
        'description' => '',
        'address' => '',
      ],
    ],
    'bing_maps_api_search_item_array' => [
      'variables' => [
        'item' => [],
      ],
    ],
  ];
}

/**
 * Preprocesses list items when objects.
 *
 * @param array $variables
 *   Array of Drupal\Core\Field\FieldItemListInterface.
 */
function template_preprocess_bing_maps_api_search_item(array &$variables) {
  $attributes = [
    'data-lat' => $variables['lat'],
    'data-lng' => $variables['long'],
  ];
  $variables['html_attributes'] = new Attribute($attributes);
}

/**
 * Preprocesses list items when arrays.
 *
 * @param array $variables
 *   Array of array.
 */
function template_preprocess_bing_maps_api_search_item_array(array &$variables) {
  // HTML element attributes.
  $attributes = [
    'data-lat' => $variables['item']['latitude'],
    'data-lng' => $variables['item']['longitude'],
  ];
  $variables['html_attributes'] = new Attribute($attributes);
  $variables['description'] = $variables['item']['description'];

  if (!empty($variables['item']['address'])) {
    $variables['address'] = $variables['item']['address'];
  }
}
