<?php

use Drupal\Core\Template\Attribute;
use Drupal\Component\Utility\String;

/**
 * Implements hook_theme().
 */
function bing_maps_api_theme() {
  return [
    'bing_maps_api_search_item' => [
      'variables' => [
        'item' => [],
      ],
    ],
    'bing_maps_api_search_item_array' => [
      'variables' => [
        'item' => [],
      ],
    ],
  ];
}

/**
 * Preprocesses list items when objects.
 *
 * @param array $variables
 *   Array of Drupal\Core\Field\FieldItemListInterface.
 *
 */
function template_preprocess_bing_maps_api_search_item(&$variables) {
  $attributes = [
    'data-lat' => $variables['item']->get('latitude')->getValue(),
    'data-lng' => $variables['item']->get('longitude')->getValue(),
  ];
  $variables['html_attributes'] = new Attribute($attributes);
  $variables['description'] = String::checkPlain($variables['item']->get('description')->getValue());

  $address = $variables['item']->get('address')->getValue();
  if (!empty($address)) {
    $variables['address'] = String::checkPlain($address);
  }
}

/**
 * Preprocesses list items when arrays.
 *
 * @param array $variables
 *   Array of array.
 *
 */
function template_preprocess_bing_maps_api_search_item_array(&$variables) {
  // HTML element attributes.
  $attributes = [
    'data-lat' => $variables['item']['latitude'],
    'data-lng' => $variables['item']['longitude'],
  ];
  $variables['html_attributes'] = new Attribute($attributes);
  $variables['description'] = String::checkPlain($variables['item']['description']);

  if (!empty($variables['item']['address'])) {
    $variables['address'] = String::checkPlain($variables['item']['address']);
  }
}
